blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸í•˜ê¸°
    url: https://github.com/mindulle/sonagi-design-system/discussions/new?category=q-a
    about: ì§ˆë¬¸ì´ë‚˜ ê¶ê¸ˆí•œ ì ì´ ìˆë‹¤ë©´ Discussionì„ ì´ìš©í•´ì£¼ì„¸ìš”.
  - name: ğŸ’¡ ì•„ì´ë””ì–´ ì œì•ˆ
    url: https://github.com/mindulle/sonagi-design-system/discussions/new?category=ideas
    about: ìƒˆë¡œìš´ ì•„ì´ë””ì–´ê°€ ìˆë‹¤ë©´ ì´ê³³ì—ì„œ ë…¼ì˜í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.